version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
<<<<<<< HEAD
  eb: circleci/aws-elastic-beanstalk@2.0.1
=======
>>>>>>> 2c26f50cbec61cf8f55d08b95036b7f27f1a37a1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
<<<<<<< HEAD
      - eb/setup
=======
>>>>>>> 2c26f50cbec61cf8f55d08b95036b7f27f1a37a1
      - run:
          name: App Dep Install
          command: |
            npm run front-end-install
      - run:
          name: Server Dep Install
          command: |
            npm run back-end-install
      - run:
          name: App Build
          command: |
            npm run front-end-build
      - run:
          name: Server Build
          command: |
            npm run back-end-build
      - run:
<<<<<<< HEAD
          name: Deploy Server
          command: |
            npm run back-end-deploy
      - run:
=======
>>>>>>> 2c26f50cbec61cf8f55d08b95036b7f27f1a37a1
          name: Deploy App
          command: |
            npm run front-end-deploy
