version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: App Dep Install
          command: |
            npm run front-end-install
      - run:
          name: Server Dep Install
          command: |
            npm run back-end-install
      - run:
          name: App Build
          command: |
            npm run front-end-build
      - run:
          name: Server Build
          command: |
            npm run back-end-build
      - run:
          name: Deploy Server
          command: |
            npm run back-end-deploy
      - run:
          name: Deploy App
          command: |
            npm run front-end-deploy
